apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: jenkins
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: jenkins
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: jenkins
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io